"""Default homepage CMS configuration — editable via Admin Site Builder."""

DEFAULT_SITE_CONFIG: dict = {
    "hero": {
        "badge": "RBI LSP Registered · Premium Marketplace",
        "headline_line1": "Dream Big.",
        "headline_highlight": "Borrow Smart.",
        "headline_sub": "Personal loans up to ₹10,00,000",
        "description": "Compare curated offers from HDFC, ICICI, Bajaj and 15+ regulated lenders — one transparent platform, zero branch visits.",
        "bullet_points": [
            "Wedding, home, medical, travel — tailored loan options",
            "Rates from 10.99% p.a. — compare and choose with clarity",
            "End-to-end digital journey from eligibility to disbursal",
        ],
        "cta_primary": "Get My Loan Offer",
        "cta_secondary": "View Interest Rates",
        "image_url": "/images/site/1463335361701-e90f4c5045d0-600x750.jpg",
        "testimonial_quote": "Shaadi ke liye apply kiya tha — teen lenders ka offer ek screen par mila. KYC ghar baithe ho gayi, 48 ghante mein paise account mein aa gaye.",
        "testimonial_author": "Priya Sharma, Pune",
        "approval_card_label": "Loan Disbursed",
        "approval_card_amount": "₹4,80,000",
        "roi_badge": "10.99%",
        "roi_badge_label": "From",
    },
    "stats": [
        {"value": "₹10L+", "label": "Max Loan"},
        {"value": "10.99%", "label": "Lowest ROI"},
        {"value": "5 Min", "label": "Fast Approval"},
        {"value": "50K+", "label": "Happy Customers"},
    ],
    "urgency_bar": {
        "enabled": False,
        "text": "",
        "emoji": "",
    },
    "promo_strip": {
        "enabled": False,
        "text": "",
        "highlight": "",
    },
    "social_proof": {
        "enabled": False,
        "viewers_base": 0,
        "label": "",
    },
    "dream_section": {
        "title": "Your Dreams Deserve the Best Rate",
        "subtitle": "Whether it's a dream wedding, your child's education, or expanding your business — we make borrowing feel effortless.",
        "cards": [
            {
                "title": "Dream Wedding",
                "desc": "Venue, jewellery, honeymoon — fund it all",
                "image": "/images/site/1519741497674-611481863552-600x400.jpg",
                "cta": "Wedding Loan",
            },
            {
                "title": "Dream Home",
                "desc": "Renovation, deposit, interiors made easy",
                "image": "/images/site/1560518883-ce09059eeffa-600x400.jpg",
                "cta": "Home Loan",
            },
            {
                "title": "Dream Business",
                "desc": "Inventory, equipment, working capital",
                "image": "/images/site/1551836022-d5d88e9218df-600x400.jpg",
                "cta": "Business Loan",
            },
        ],
    },
    "theme": {
        "accent": "teal",
        "hero_style": "premium",
        "background": "glass-blue",
        "hero_overlay": "sky-glass",
        "glass_intensity": "high",
        "hero_background": "/hero-wedding-couple.png",
    },
    "sections": {
        "urgency_bar": False,
        "promo_strip": False,
        "social_proof": False,
        "dream_section": True,
        "metrics_ticker": True,
        "emi_calculator": True,
        "testimonials": True,
        "cta_band": True,
        "faq": True,
        "how_it_works": True,
        "loan_products": True,
    },
    "trust_band": {
        "tagline": "Trusted by 50,000+ customers",
        "features": [
            "No Hidden Charges",
            "Flexible Tenure Options",
            "Minimal Documentation",
            "End-to-End Digital Journey",
        ],
    },
    "metrics_ticker": [
        {"value": "15+", "label": "Partner Lenders"},
        {"value": "₹250Cr+", "label": "Loans Facilitated"},
        {"value": "5 min", "label": "Avg. Approval Time"},
        {"value": "4.8/5", "label": "Customer Rating"},
        {"value": "100%", "label": "Digital KYC"},
    ],
    "testimonials_section": {
        "badge": "Real Customer Stories",
        "title": "Bharat Bhar Ke Vishwas",
        "title_highlight": "Vishwas",
        "subtitle": "Verified reviews from customers across India — wedding, medical, business, and everyday goals.",
        "items": [
            {
                "name": "Priya Sharma",
                "city": "Pune, Maharashtra",
                "amount": "₹3,20,000",
                "purpose": "Wedding expenses",
                "date": "June 2026",
                "quote": "Meri shaadi ke liye urgent funds chahiye the. Teen lenders ka offer ek hi jagah mila — ICICI ka EMI sabse kam tha.",
                "rating": "5",
                "image": "/images/site/1463335361701-e90f4c5045d0-600x750.jpg",
            },
            {
                "name": "Arjun Menon",
                "city": "Kochi, Kerala",
                "amount": "₹1,85,000",
                "purpose": "Medical emergency",
                "date": "May 2026",
                "quote": "Papa ki surgery ke liye raat ko apply kiya. Subah tak HDFC se approval mil gaya.",
                "rating": "5",
                "image": "/images/site/1576091160550-2173dba999ef-600x400.jpg",
            },
            {
                "name": "Kavita Joshi",
                "city": "Jaipur, Rajasthan",
                "amount": "₹4,75,000",
                "purpose": "Shop expansion",
                "date": "April 2026",
                "quote": "Apni boutique ke liye working capital chahiye tha. Paperless process tha — branch gaye bina loan mil gaya.",
                "rating": "4.9",
                "image": "/images/site/1551836022-d5d88e9218df-600x400.jpg",
            },
        ],
    },
    "faq_section": {
        "title": "Questions? We Have Answers",
        "title_highlight": "We Have Answers",
        "subtitle": "Full transparency — no hidden charges",
        "items": [
            {
                "q": "Does Neer Loan Solutions lend money directly?",
                "a": "No. We are a Loan Service Provider (LSP). We connect you with partner banks and NBFCs.",
            },
            {
                "q": "How much loan can I get?",
                "a": "Personal loans from ₹50,000 up to ₹5,00,000 depending on your income and credit profile.",
            },
            {
                "q": "How long does approval take?",
                "a": "Eligibility check takes 2–5 minutes. Final approval is usually same day or within 24 hours.",
            },
            {
                "q": "What documents are required?",
                "a": "Mobile number, PAN, and basic details. Full digital KYC includes Aadhaar OTP and bank verification.",
            },
            {
                "q": "What are the interest rates?",
                "a": "Rates start from 10.99% with partner lenders. You receive multiple offers and choose the best.",
            },
            {
                "q": "Is there a prepayment penalty?",
                "a": "It depends on the lender. Many partners offer zero foreclosure charges — shown in each offer.",
            },
        ],
    },
    "cta_band": {
        "badge": "Institutional-grade lending",
        "title": "Compare offers with confidence",
        "title_highlight": "confidence",
        "subtitle": "Select from regulated partner lenders, review terms transparently, and complete your application entirely online.",
        "image": "/images/site/1529156069898-49953e39b3ac-1920x600.jpg",
        "cta_primary": "Start Application",
        "cta_secondary": "Explore Loan Types",
    },
    "how_it_works": {
        "title": "How It Works",
        "subtitle": "From application to disbursal — fully digital",
        "steps": [
            {"title": "Apply Online", "desc": "Enter mobile, verify OTP, share basic details"},
            {"title": "Check Eligibility", "desc": "Instant eligibility across partner lenders"},
            {"title": "Compare Offers", "desc": "Side-by-side rates, EMI, and tenure"},
            {"title": "Complete KYC", "desc": "Aadhaar OTP, bank verify, eSign — from home"},
        ],
    },
    "loan_products": {
        "title": "Loans for Every Life Goal",
        "cards": [
            {"title": "Personal", "rate": "10.99%", "image": "/images/site/1463335361701-e90f4c5045d0-600x750.jpg"},
            {"title": "Medical", "rate": "11.49%", "image": "/images/site/1576091160550-2173dba999ef-600x400.jpg"},
            {"title": "Wedding", "rate": "11.99%", "image": "/images/site/1519741497674-611481863552-600x400.jpg"},
            {"title": "Business", "rate": "12.49%", "image": "/images/site/1551836022-d5d88e9218df-600x400.jpg"},
        ],
    },
    "business_model": {
        "badge": "Business Model",
        "title": "Personal Loan Marketplace",
        "subtitle": "Connect customers with multiple lenders. Earn commission on every disbursal.",
        "steps": [
            {"step": "01", "title": "Customer Visits", "desc": "Discovers Neer Loan Solutions"},
            {"step": "02", "title": "Basic Details", "desc": "OTP-verified profile capture"},
            {"step": "03", "title": "Partner APIs", "desc": "Parallel lender offer engine"},
            {"step": "04", "title": "Best Offers", "desc": "AI-ranked comparison UI"},
            {"step": "05", "title": "Select & KYC", "desc": "Digital verification & eSign"},
            {"step": "06", "title": "Disbursal", "desc": "Direct to customer account"},
        ],
    },
    "platform": {
        "badge": "Platform",
        "title": "Enterprise-Grade Architecture",
        "subtitle": "Six-phase product roadmap — from lead capture to admin analytics. Built for scale.",
        "cta": "View Platform Details",
        "phases": [
            {
                "phase": "Phase 1",
                "title": "Lead Capture",
                "items": ["OTP login", "PAN validation", "Consent & disclosure", "Lead database"],
            },
            {
                "phase": "Phase 2",
                "title": "Offer Engine",
                "items": ["Partner API integration", "Parallel offer fetch", "Best-deal ranking", "Offer selection"],
            },
            {
                "phase": "Phase 3",
                "title": "KYC Flow",
                "items": ["Aadhaar eKYC", "Bank penny drop", "Document upload", "Digital eSign"],
            },
            {
                "phase": "Phase 4",
                "title": "Processing",
                "items": ["Status tracking", "Partner webhooks", "SMS notifications", "Disbursal alerts"],
            },
            {
                "phase": "Phase 5",
                "title": "Dashboard",
                "items": ["User portal", "EMI schedule", "Neer AI assistant", "Agreement download"],
            },
            {
                "phase": "Phase 6",
                "title": "Admin & Scale",
                "items": ["Lead funnel analytics", "Commission reports", "Fraud rules", "Role-based access"],
            },
        ],
    },
    "premium_features": {
        "badge": "Differentiators",
        "title": "Built Beyond Standard Marketplaces",
        "items": [
            {"title": "AI Offer Recommendations", "desc": "Neer AI ranks offers by your profile and repayment capacity."},
            {"title": "Pre-Approved Offers", "desc": "Soft-pull eligibility signals for faster decisions."},
            {"title": "Instant Approval Score", "desc": "Real-time probability engine before you apply."},
            {"title": "Smart Lead Scoring", "desc": "ML-powered lead quality for partner lenders."},
            {"title": "Fraud Detection", "desc": "Multi-layer verification and anomaly monitoring."},
            {"title": "WhatsApp Tracking", "desc": "Status updates and support on WhatsApp."},
        ],
    },
    "trust_gallery": {
        "title": "Trusted by Thousands Across India",
        "subtitle": "From Mumbai to Delhi — professionals, families, and entrepreneurs trust Neer Loan Solutions.",
        "images": [
            "/images/site/1463335361701-e90f4c5045d0-600x750.jpg",
            "/images/site/1519741497674-611481863552-600x400.jpg",
            "/images/site/1551836022-d5d88e9218df-600x400.jpg",
            "/images/site/1576091160550-2173dba999ef-600x400.jpg",
        ],
    },
    "lifestyle_showcase": {
        "blocks": [
            {
                "title": "Home, Wedding, Dreams — All Possible",
                "desc": "Neer Loan Solutions connects you with India's trusted banks and NBFCs. Compare offers, choose the best rate, and receive funds directly in your account.",
                "image": "/images/site/1560518883-ce09059eeffa-600x400.jpg",
                "cta": "Explore Loans",
                "href": "/loans",
            },
            {
                "title": "100% Digital. Zero Branch Visits.",
                "desc": "OTP login, Aadhaar eKYC, bank verification, digital eSign — the entire process from your phone. Get approved from home.",
                "image": "/images/site/1529156069898-49953e39b3ac-1920x600.jpg",
                "cta": "Start Application",
                "href": "/apply",
            },
        ],
    },
    "app_download": {
        "badge": "Mobile App — Coming Soon",
        "title": "Neer Loan App — Loans in Your Pocket",
        "subtitle": "Track applications, compare offers, EMI calculator — all in one premium app. Launching Q3 2026.",
        "cta": "Join Waitlist →",
        "image": "/images/site/1529156069898-49953e39b3ac-1920x600.jpg",
    },
    "refer_banner": {
        "title": "Refer & Earn",
        "subtitle": "Earn rewards on every successful referral disbursal",
        "cta": "View Program",
        "image": "/images/site/1463335361701-e90f4c5045d0-600x750.jpg",
    },
    "footer": {
        "description": "India's premium personal loan marketplace. Compare offers from 15+ regulated partner banks and NBFCs.",
        "legal_note": "Licensed marketplace · Regulated partners only",
    },
    "element_styles": {},
    "custom_blocks": [],
}
