export const BRAND = {
  name: "Neer Loan Solutions",
  legalName: "Neer Loan Solutions",
  appName: "NeerCred",
  shortName: "NeerCred",
  tagline: "Dream Big. Borrow Smart.",
  logoTagline: "Dream Big. Borrow Smart.",
  logoSubtagline: "LOANS MADE SIMPLE",
  colors: {
    navy: "#004B4D",
    teal: "#004B4D",
    mint: "#2DB2A2",
    gold: "#D4A017",
    logoBay: "#FEFEFE",
  },
  email: "support@neerloansolutions.com",
  grievanceEmail: "grievance@neerloansolutions.com",
  dpoEmail: "dpo@neerloansolutions.com",
  phone: "+91 98765 43210",
  whatsapp: "919876543210",
  address: "Neer Loan Solutions, Andheri East, Mumbai, Maharashtra 400069",
  rbiNote: "RBI LSP Registered Platform",
} as const;
