export const BRAND = {
  name: "Neer Loan Solutions",
  legalName: "Neer Loan Solutions",
  appName: "NeerCred",
  shortName: "NeerCred",
  tagline: "Purity & Trust",
  logoTagline: "Purity & Trust",
  colors: {
    navy: "#0B1220",
    teal: "#0F766E",
    cyan: "#0891B2",
    gold: "#D4A017",
  },
  email: "support@neerloansolutions.com",
  grievanceEmail: "grievance@neerloansolutions.com",
  dpoEmail: "dpo@neerloansolutions.com",
  phone: "+91 98765 43210",
  whatsapp: "919876543210",
  address: "Neer Loan Solutions, Andheri East, Mumbai, Maharashtra 400069",
  rbiNote: "RBI LSP Registered Platform",
} as const;
